### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by miledaoun** [NikKovV/SDWebImage-CircularProgressView#1]
Whenever I add the pod to the podfile and install, I get build errors in Xcode. Mainly:

Expected type
Function expects 3 parameters but  found 2

**Comment by NikKovIos** [comment]
Could you please tell what language (Swift or Objective-C), Xcode version, pod, cocoapods and SdWebImage version you use?

**Comment by miledaoun** [comment]
Swift, Xcode 9.2, pod 1.4.0, SdWebimage 4.3.3

**Comment by miledaoun** [comment]
The issue is that your extension is still using SDWebimageCompletionBlock in its methods' signature but SDWebimage have changed it to SDExternalCompletionBlock. If you can update it so we don't modify the pod each time we install it

Appreciated

**Comment by miledaoun** [comment]
In addition, SDWebImageDownloaderProgressBlock now accepts an additional targetURL parameters which makes the total parameters 3 but your extension is not handling this yet

**Comment by NikKovIos** [comment]
Could you please submit a pr?
